repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-builtin-literals
        args: ['--no-allow-dict-kwargs']
    -   id: check-docstring-first
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
        exclude: '.*\.txt$'
    -   id: name-tests-test
    -   id: flake8
        args: ['--max-line-length', '120']
    -   id: trailing-whitespace
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.6.1
    hooks:
    -   id: reorder-python-imports
        language_version: python3
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v1.4.1
    hooks:
        - id: add-trailing-comma
-   repo: https://github.com/Yelp/detect-secrets.git
    rev: v1.4.0
    hooks:
    -   id: detect-secrets
        name: Detect secrets
        language: python
        entry: detect-secrets-hook
        args: ['scan']