apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-api-deployment
  namespace: ml-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-api
  template:
    metadata:
      labels:
        app: ml-api
    spec:
      containers:
      - name: ml-api
        image: registry-c6af1e1a-8717-4821-9c1f-895998bf4e9c.cytr.us/portfolio/ml-api:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "4"
            memory: "8Gi"
        envFrom:
        - secretRef:
            name: postgres-secret
      imagePullSecrets:
      - name: gitea-creds