apiVersion: v1
kind: Service
metadata:
  name: ml-api-service
  namespace: ml-api
spec:
  type: NodePort
  selector:
    app: ml-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000