name: Build and push ml endpoint

env:
  TAG: $(echo ${GITHUB_SHA::8}-$(date +'%Y-%m-%d'))
  REPO_NAME: portfolio
  APP_NAME: ml-api

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN  }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          registry: srv17.mikr.us:40073

      - name: build and push
        run: |
          docker build \
          -t srv17.mikr.us:40073/${{ env.REPO_NAME }}/${{ env.APP_NAME}}:${{ env.TAG }} \
          -f Dockerfile .

          docker push srv17.mikr.us:40073/${{ env.REPO_NAME }}/${{ env.APP_NAME}}:${{ env.TAG }}
          
          docker build \
          -t srv17.mikr.us:40073/${{ env.REPO_NAME }}/${{ env.APP_NAME}}:latest \
          -f Dockerfile .
          
          docker push srv17.mikr.us:40073/${{ env.REPO_NAME }}/${{ env.APP_NAME}}:latest
  redeploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        run: |
          cd kubernetes && sh create_secrets_and_deploy.sh \
          ${{ secrets.DOCKERHUB_LOGIN  }} \
          ${{ secrets.DOCKERHUB_TOKEN }}